-- demo_talepleri: pazarlama sitesi demo formu kayitlari (app/api/demo/route.ts).
-- Tablo baslangicta Supabase SQL editorunden elle olusturulmustu; repo'nun
-- sifirdan kurulabilir olmasi icin semasi burada migration olarak tanimlanir.
-- Mevcut projede tablo zaten var oldugundan "if not exists" ile idempotenttir.
--
-- Guvenlik modeli: bu tabloya yalnizca sunucu tarafinda dogrudan Postgres
-- baglantisiyla (lib/db.ts, RLS'yi bypass eden postgres rolu) yazilir.
-- anon/authenticated rollerinin PostgREST uzerinden hicbir erisime ihtiyaci
-- yok; anon key istemci bundle'inda herkese acik oldugu icin acik birakilan
-- bir grant, tum demo taleplerinin disaridan okunup silinebilmesi anlamina
-- gelirdi. Bu yuzden RLS acilir ve tum grant'ler geri alinir.

create table if not exists demo_talepleri (
  id bigint generated by default as identity primary key,
  otel_adi text not null,
  oda_sayisi integer not null,
  email text not null,
  telefon text not null,
  mesaj text,
  kvkk_onay boolean not null default false,
  created_at timestamptz not null default now()
);

alter table demo_talepleri enable row level security;
revoke all on demo_talepleri from anon, authenticated;
